server:
  port: 9000

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              client-id: "admin-client"
              # the client secret is "secret" (without quotes)
              client-secret: "{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC"
              client-authentication-methods: "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris: "http://127.0.0.1:8080/login/oauth2/code/spring"
              scopes:
                - "openid"
                - "user:read"
                - "user:write"
            token:
              access-token-time-to-live: 30s
            require-authorization-consent: true
          client-2:
            registration:
              client-id: "service-client"
              client-secret: "{bcrypt}$2a$10$zvB3W4vNVDYe13CBRI5wuexs2QI3yUpViH7cG0L17TExboS4bd9BG"
              client-authentication-methods: "client_secret_basic"
              authorization-grant-types:
                - "client_credentials"
              scopes:
                - "user:read"

logging:
  level:
    org.springframework.security: trace